codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 100%
        if_ci_failed: error

flags:
  agent:
    paths:
      - chronos-rust/chronos-agent/
  crypto:
    paths:
      - chronos-rust/chronos-crypto/
  core:
    paths:
      - chronos-rust/chronos-core/
  net:
    paths:
      - chronos-rust/chronos-net/
  python:
    paths:
      - "*.py"
